/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as MaterialSlugRouteImport } from './routes/material.$slug'
import { Route as MonumentsIndexRouteImport } from './routes/monuments.index'
import { Route as MonumentsSlugRouteImport } from './routes/monuments.$slug'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialSlugRoute = MaterialSlugRouteImport.update({
  id: '/material/$slug',
  path: '/material/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MonumentsIndexRoute = MonumentsIndexRouteImport.update({
  id: '/monuments/',
  path: '/monuments/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonumentsSlugRoute = MonumentsSlugRouteImport.update({
  id: '/monuments/$slug',
  path: '/monuments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/guides': typeof GuidesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/material/$slug': typeof MaterialSlugRoute
  '/monuments/$slug': typeof MonumentsSlugRoute
  '/monuments/': typeof MonumentsIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/guides': typeof GuidesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/material/$slug': typeof MaterialSlugRoute
  '/monuments/$slug': typeof MonumentsSlugRoute
  '/monuments': typeof MonumentsIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/guides': typeof GuidesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/material/$slug': typeof MaterialSlugRoute
  '/monuments/$slug': typeof MonumentsSlugRoute
  '/monuments/': typeof MonumentsIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/community'
    | '/contact'
    | '/gallery'
    | '/guides'
    | '/partners'
    | '/privacy'
    | '/services'
    | '/suppliers'
    | '/terms'
    | '/category/$slug'
    | '/material/$slug'
    | '/monuments/$slug'
    | '/monuments/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/community'
    | '/contact'
    | '/gallery'
    | '/guides'
    | '/partners'
    | '/privacy'
    | '/services'
    | '/suppliers'
    | '/terms'
    | '/category/$slug'
    | '/material/$slug'
    | '/monuments/$slug'
    | '/monuments'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/community'
    | '/contact'
    | '/gallery'
    | '/guides'
    | '/partners'
    | '/privacy'
    | '/services'
    | '/suppliers'
    | '/terms'
    | '/category/$slug'
    | '/material/$slug'
    | '/monuments/$slug'
    | '/monuments/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GuidesRoute: typeof GuidesRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SuppliersRoute: typeof SuppliersRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  MaterialSlugRoute: typeof MaterialSlugRoute
  MonumentsSlugRoute: typeof MonumentsSlugRoute
  MonumentsIndexRoute: typeof MonumentsIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$slug': {
      id: '/material/$slug'
      path: '/material/$slug'
      fullPath: '/material/$slug'
      preLoaderRoute: typeof MaterialSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monuments/': {
      id: '/monuments/'
      path: '/monuments'
      fullPath: '/monuments/'
      preLoaderRoute: typeof MonumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monuments/$slug': {
      id: '/monuments/$slug'
      path: '/monuments/$slug'
      fullPath: '/monuments/$slug'
      preLoaderRoute: typeof MonumentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GuidesRoute: GuidesRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SuppliersRoute: SuppliersRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  MaterialSlugRoute: MaterialSlugRoute,
  MonumentsSlugRoute: MonumentsSlugRoute,
  MonumentsIndexRoute: MonumentsIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
